Spring:

#H2 DataBase

  Datasource:
    url: jdbc:h2:mem:~/fiap
    username: Smarttech
    password: 
    driverClassName: org.h2.Driver

  Jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  H2:
    console:
      enabled: true
      path: /h2
      
# ğğ‘ğğ‰ğ„ğ‚ğ“'ğ’ ğ‘ğ„ğğğ’ğˆğ“ğğ‘ğ˜ : https://github.com/LlynS2/Connection_BRQ